config/routes.rb
Rails.application.routes.draw do

  resources :fields

  resources :categories

  resources :jobapplications

  resources :jobseekers

  resources :employers

  resources :jobs
  root :to => 'jobs#index'
  resources :admins
  get 'login'=>'home#login'
  post 'login_check'=> 'home#login_check'
  get 'logout' => 'home#logout'
  get 'jobapplication_lists'=>'jobapplications#list_applications'
  get '/search'=> 'jobs#search'
  get 'recommended' => 'jobs#recommendation'
  get 'jobapps'=> 'jobapplications#list_apps'
  get 'delete_employer' => 'employers#list_employer'
  get 'view_my_applications' => 'jobseekers#view_my_applications'
  match '*a', :to => 'errors#routing', via: :get

end

app/views/admins/_form.html.erb
<% def error_span(attribute) %>

<% end    %>

<%= form_for @admin, :html => { :class => "form-horizontal admin" } do |f| %>

    <% if @admin.errors.any? %>
        <div id="error_expl" class="panel panel-danger">
          <div class="panel-heading">
            <h3 class="panel-title"><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h3>
          </div>
          <div class="panel-body">
            <ul>
              <% @admin.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
    <% end %>

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name,:required=>true, :class => 'form-control'%>
      </div>
      <%# error_span(@admin[:name]) %>
    </div>
    <div class="control-group">
      <%= f.label :email, :class => 'control-label' %>
      <div class="controls">
        <%= f.email_field :email, :required=>true, :class => 'form-control' %>
      </div>
      <%# error_span(@admin[:email]) %>
    </div>
    <div class="control-group">
      <%= f.label :password, :class => 'control-label' %>
      <div class="controls">
        <%= f.password_field :password,:required=>true,  :class => 'form-control' %>
      </div>
      <%# error_span(@admin[:password]) %>
    </div>


    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admins_path, :class => 'btn btn-default' %>

<% end %>

app/views/admins/edit.html.erb
<%- model_class = Admin -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admins/index.html.erb
<%- model_class = Admin -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <% if((cookies[:adminID]!="") && (!cookies[:adminID].is_a?NilClass)) %>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= link_to admin.id, admin_path(admin) %></td>
        <td><%= admin.name %></td>
        <td><%= admin.email %></td>
        <td><%=l admin.created_at %></td>
        <% if((cookies[:adminID]!="") && (!cookies[:adminID].is_a?NilClass)) %>
        <td>
          <% if(admin.email!="ad.direwolf.min@gmail.com") %>

          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_path(admin), :class => 'btn btn-default btn-xs' %>
          <%# link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_path(admin),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
          <% end %>

          </td>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%# link_to t('.new', :default => t("helpers.links.new")),
            new_admin_path,
            :class => 'btn btn-primary' %>

<%# link_to "Create Employer",new_employer_path, :class => 'btn btn-primary'%>

app/views/admins/new.html.erb
<%- model_class = Admin -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admins/show.html.erb
<%- model_class = Admin -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @admin.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @admin.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:password) %>:</strong></dt>
  <dd><%= @admin.password %></dd>
</dl>

<%# link_to t('.back', :default => t("helpers.links.back")),
              admins_path, :class => 'btn btn-default'  %>
<% if((cookies[:adminID]!="") && (!cookies[:adminID].is_a?NilClass)) %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_admin_path(@admin), :class => 'btn btn-default' %>
<%# link_to t('.destroy', :default => t("helpers.links.destroy")),
              admin_path(@admin),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>


    <%= link_to "Create Other Admins",new_admin_path, :class => 'btn btn-primary'%>
    <%= link_to "Create Employer",new_employer_path, :class => 'btn btn-primary'%>
    <%= link_to "Delete Employer", delete_employer_path, :class => 'btn btn-primary'%>
    <%= link_to "Create Category",new_category_path, :class => 'btn btn-primary'%>
<% end %>