config/routes.rb
Rails.application.routes.draw do

  resources :fields

  resources :categories

  resources :jobapplications

  resources :jobseekers

  resources :employers

  resources :jobs
  root :to => 'jobs#index'
  resources :admins
  get 'login'=>'home#login'
  post 'login_check'=> 'home#login_check'
  get 'logout' => 'home#logout'
  get 'jobapplication_lists'=>'jobapplications#list_applications'
  get '/search'=> 'jobs#search'
  get 'recommended' => 'jobs#recommendation'
  get 'jobapps'=> 'jobapplications#list_apps'
  get 'delete_employer' => 'employers#list_employer'
  get 'view_my_applications' => 'jobseekers#view_my_applications'
  match '*a', :to => 'errors#routing', via: :get

end

app/models/job.rb
class Job < ActiveRecord::Base
=begin
 attr_accessible :job_id, :title, :description, :tag1, :tag2, :tag3, :category, :deadline
=end
belongs_to :employer
belongs_to :category
  def category
    category_name
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
    if(@jobs.count==0)
      @custom_notification = "No jobs to show"
      render "layouts/notifications"
      return
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
    if((cookies[:employerID]=="")||(cookies[:employerID].is_a?NilClass))
      @custom_error = "Insufficient Rights. Please login as employer !"
      render "layouts/error"
      return
    end
    @employer = Employer.find(cookies[:employerID].to_i)
    @job.employer_id=@employer.id
  end

  def recommendation
    @jobs = []
    Jobapplication.where(:jobseeker_id => cookies[:jobseekerID]).to_a.each do |app|
      job = Job.find(app.job_id)
      @jobs += Job.where(:tag1 => job.tag1)
      @jobs += Job.where(:tag2 => job.tag2)
      @jobs += Job.where(:tag3 => job.tag3)
      @jobs.delete job
    end
    @jobs.uniq!
    if(@jobs.count==0)
      render 'layouts/no_recommended_jobs'
      return
    elsif (@jobs.count!=0)
      render :index
    end
  end

  def search
    @jobs=[]
    @searchStr = params[:search] if (@searchStr.is_a? NilClass)
    if(@searchStr=="")
      @jobs = Job.all
    elsif
    @searchStr.split.each do |word|
      Job.find_each do |job|
        if(( (job.title =~ /#{"(.*)"+word+"(.*)"}/i) == 0) ||
        ((job.tag1 =~ /#{"(.*)"+word+"(.*)"}/i) == 0) ||((job.tag2 =~ /#{"(.*)"+word+"(.*)"}/i) == 0) ||((job.tag3 =~ /#{"(.*)"+word+"(.*)"}/i) == 0)||
        ((job.category =~ /#{"(.*)"+word+"(.*)"}/i) == 0))
                    @jobs << job
        end
      end
    end
    end
    @jobs.uniq!
    if(@jobs.count==0)
      @custom_notification = "No such job found"
      render "layouts/notifications"
      return
    elsif (@jobs.count!=0)
      render :index
    end
  end


  # GET /jobs/1/edit
  def edit

    if((cookies[:employerID]=="")||(cookies[:employerID].is_a?NilClass))
      @custom_error = "Insufficient Rights. Please login as employer !"
      render "layouts/error"
      return

    end
    @job.category_name = Category.find_by_name(@job.category_name).id
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)
    @job.category_name = Category.find(@job.category_name.to_i).name
    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    params[:job][:category_name] = Category.find(params[:job][:category_name]).name
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    if((cookies[:employerID]=="")||(cookies[:employerID].is_a?NilClass))
      @custom_error = "Insufficient Rights. Please login as employer !"
      render "layouts/error"
      return
    end
    Jobapplication.find_each do |app|
      Jobapplication.delete(app) if app.job_id == @job.id
    end
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:job_id, :title, :description, :tag1, :tag2, :tag3, :category_name, :deadline, :employer_id)
    end

  def error_span(attribute)
    @template.content_tag :span, errors_for(attribute), class: 'help-inline'
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for @job, :html => { :class => "form-horizontal job" } do |f| %>

    <% if @job.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h3>
      </div>
      <div class="panel-body">
      <ul>
        <% @job.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title,:required=>true,  :class => 'form-control' %>
    </div>
   <!-- <%# error_span(@job[:title]) %>-->
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :required=>true, :class => 'form-control' %>
    </div>
 <!--   <%# error_span(@job[:description]) %>-->
  </div>
  <div class="control-group">
    <%= f.label :tag1, :class => 'control-label' %>
    <div class="controls">
      <%=  f.select :tag1, options_for_select(%w[Internship Full-Time Part-Time Co-Op Contractor]) %>
    </div>
  <!--  <%# error_span(@job[:tag1]) %>-->
  </div>
  <div class="control-group">
    <%= f.label :tag2, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :tag2, options_for_select(%w[Office Freelance Work-From-Home]) %>
    </div>
  <!--  <%# error_span(@job[:tag2]) %>-->
  </div>
  <div class="control-group">
    <%= f.label :tag3, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :tag3, options_for_select(%w[All American-Indian Asian White/Caucasian African-American Hispanic/Latino Native-Hawaiian Other-Pacific-Islander]) %>
    </div>
  <!--  <%# error_span(@job[:tag3]) %>-->
  </div>
  <div class="control-group">
    <%= f.label :category, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :category_name, Category.all.collect{ |c| [c.name, c.id]} %>
    </div>
   <!-- <%# error_span(@job[:category_name]) %>-->
  </div>
  <div class="control-group">
    <%= f.label :deadline, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :deadline, :class => 'form-control' %>
    </div>
<!--    <%# error_span(@job[:deadline]) %>-->
  </div>


 <!-- <div class="control-group">
    <%# f.label :employer_id, :class => 'control-label' %>
    <div class="controls">
      <%# f.number_field :employer_id, :class => 'form-control' %>
    </div>
    <%# error_span(@job[:employer_id]) %>
  </div>

-->
   <%= f.hidden_field :employer_id  %>
  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            jobs_path, :class => 'btn btn-default' %>

<% end %>

app/views/jobs/edit.html.erb
<%- model_class = Job -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/jobs/index.html.erb
<%- model_class = Job -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:tag1) %></th>
      <th><%= model_class.human_attribute_name(:tag2) %></th>
      <th><%= model_class.human_attribute_name(:tag3) %></th>
      <th><%= model_class.human_attribute_name(:category) %></th>
      <th><%= model_class.human_attribute_name(:deadline) %></th>
      <th><%= model_class.human_attribute_name(:employer_id) %></th>
      <% if((cookies[:employerID]!="") && (!cookies[:employerID].is_a?NilClass)) %>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= link_to job.id, job_path(job) %></td>
        <td><%= job.title %></td>
        <td><%= job.description %></td>
        <td><%= job.tag1 %></td>
        <td><%= job.tag2 %></td>
        <td><%= job.tag3 %></td>
        <td><%= job.category %></td>
        <td><%= job.deadline %></td>
        <td><%= job.employer_id%></td>
        <td>


          <%= link_to t('.show', :default => t("helpers.links.show")),
                      job_path(job), :class => 'btn btn-default btn-xs' %>

          <% if((cookies[:employerID]!="") && (!cookies[:employerID].is_a?NilClass)) %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_job_path(job), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      job_path(job),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>

          <% end %>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%# link_to t('.new', :default => t("helpers.links.new")),
            new_job_path,
            :class => 'btn btn-primary' %>

app/views/jobs/new.html.erb
<%- model_class = Job -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/jobs/show.html.erb
<%- model_class = Job -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">

  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @job.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @job.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tag1) %>:</strong></dt>
  <dd><%= @job.tag1 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tag2) %>:</strong></dt>
  <dd><%= @job.tag2 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tag3) %>:</strong></dt>
  <dd><%= @job.tag3 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:category) %>:</strong></dt>
  <dd><%= @job.category %></dd>
  <dt><strong><%= model_class.human_attribute_name(:deadline) %>:</strong></dt>
  <dd><%= @job.deadline %></dd>
  <dt><strong><%= model_class.human_attribute_name(:employer_id) %>:</strong></dt>
  <dd><%= @job.employer_id %></dd>
</dl>

<%# link_to t('.back', :default => t("helpers.links.back")),
              jobs_path, :class => 'btn btn-default'  %>

<% if((cookies[:employerID]!="") && (!cookies[:employerID].is_a?NilClass)) %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_job_path(@job), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              job_path(@job),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
<% end %>
<% if((cookies[:employerID]=="") || (cookies[:employerID].is_a?NilClass)) %>
<%= link_to "Apply to Job", new_jobapplication_path(:job_id=>@job.id) , :class => 'btn btn-primary'%>
<% end %>
<% if ((cookies[:employerID]!="") && (!cookies[:employerID].is_a?NilClass)) %>
<%= link_to "View Job Applications", jobapplication_lists_path(:job_id=>@job.id) , :class => 'btn btn-primary'%>
<% end %>