config/routes.rb
Rails.application.routes.draw do

  resources :fields

  resources :categories

  resources :jobapplications

  resources :jobseekers

  resources :employers

  resources :jobs
  root :to => 'jobs#index'
  resources :admins
  get 'login'=>'home#login'
  post 'login_check'=> 'home#login_check'
  get 'logout' => 'home#logout'
  get 'jobapplication_lists'=>'jobapplications#list_applications'
  get '/search'=> 'jobs#search'
  get 'recommended' => 'jobs#recommendation'
  get 'jobapps'=> 'jobapplications#list_apps'
  get 'delete_employer' => 'employers#list_employer'
  get 'view_my_applications' => 'jobseekers#view_my_applications'
  match '*a', :to => 'errors#routing', via: :get

end

app/models/employer.rb
class Employer < ActiveRecord::Base
  has_many :jobs
  belongs_to :admin

  def name
    contact_name
  end
end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController
  before_action :set_employer, only: [:show, :edit, :update, :destroy]

  # GET /employers
  # GET /employers.json
  def index
    @employers = Employer.all
  end

  # GET /employers/1
  # GET /employers/1.json
  def show
  end

  def list_employer
       @employers = Employer.where(:admin_id => cookies[:adminID].to_i).to_a
       render :index
  end

  # GET /employers/new
  def new
    @employer = Employer.new
    if((cookies[:adminID]=="")||(cookies[:adminID].is_a?NilClass))
      @custom_error = "Insufficient Rights. Please login as admin!"
      render "layouts/error"
      return
    end
    @admin = Admin.find(cookies[:adminID].to_i)
    @employer.admin_id=@admin.id
  end

  # GET /employers/1/edit
  def edit
    if((@employer.email=="empl.direwolf.oyer@gmail.com"))
      @custom_error = "Action Not Allowed ! This is a SYSTEM DEFINED Employer. Please create sample Employer and perform this action"
      render "layouts/error"
      return
    end
    if((cookies[:adminID]=="")||(cookies[:adminID].is_a?NilClass))
      @custom_error = "Insufficient Rights.Please login as admin!"
      render "layouts/error"
      return
    end
  end

  # POST /employers
  # POST /employers.json
  def create
    @employer = Employer.new(employer_params)

    respond_to do |format|
      if @employer.save
        UserNotifier.send_signup_email(@employer).deliver
        format.html { redirect_to @employer, notice: 'Employer was successfully created.' }
        format.json { render :show, status: :created, location: @employer }
      else
        format.html { render :new }
        format.json { render json: @employer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employers/1
  # PATCH/PUT /employers/1.json
  def update
    if((@employer.email=="empl.direwolf.oyer@gmail.com"))
      @custom_error = "Action Not Allowed ! This is a SYSTEM DEFINED Employer. Please create sample Employer and perform this action"
      render "layouts/error"
      return
    end
    respond_to do |format|
      if @employer.update(employer_params)
        format.html { redirect_to @employer, notice: 'Employer was successfully updated.' }
        format.json { render :show, status: :ok, location: @employer }
      else
        format.html { render :edit }
        format.json { render json: @employer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employers/1
  # DELETE /employers/1.json
  def destroy
    if((@employer.email=="empl.direwolf.oyer@gmail.com"))
      @custom_error = "Action Not Allowed ! This is a SYSTEM DEFINED Employer. Please create sample Employer and perform this action"
      render "layouts/error"
      return
    end
    if((cookies[:adminID]=="")||(cookies[:adminID].is_a?NilClass))
      @custom_error = "Insufficient Rights.Please login as admin!"
      render "layouts/error"
      return
    end
    Job.where(:employer_id => @employer.id).to_a.each do |job|
      Jobapplication.where(:job_id => job.id).to_a.each do |jobapp|
        Jobapplication.delete(jobapp.id)
      end
      Job.delete(job.id)
    end
    @employer.destroy
    respond_to do |format|
      format.html { redirect_to employers_url, notice: 'Employer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employer
      @employer = Employer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employer_params
      params.require(:employer).permit(:company_name, :contact_name, :email, :password, :admin_id)
    end
end

app/helpers/employer_helper.rb
module EmployerHelper
end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/views/employers/_form.html.erb
<%= form_for @employer, :html => { :class => "form-horizontal employer" } do |f| %>

    <% if @employer.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@employer.errors.count, "error") %> prohibited this employer from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @employer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :company_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :company_name,:required=>true,  :class => 'form-control' %>
    </div>
    <%# error_span(@employer[:company_name]) %>
  </div>
  <div class="control-group">
    <%= f.label :contact_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :contact_name, :required=>true, :class => 'form-control' %>
    </div>
    <%# error_span(@employer[:contact_name]) %>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.email_field :email,:required=>true,  :class => 'form-control' %>
    </div>
    <%# error_span(@employer[:email]) %>
  </div>
  <div class="control-group">
    <%= f.label :password, :class => 'control-label' %>
    <div class="controls">
      <%= f.password_field :password,:required=>true,  :class => 'form-control' %>
    </div>
    <%# error_span(@employer[:password]) %>
  </div>
  <%= f.hidden_field :admin_id  %>
<!--
  <div class="control-group">
    <%# f.label :admin_id, :class => 'control-label' %>
    <div class="controls">
      <%# f.text_field :admin_id, :class => 'form-control' %>
    </div>
    <%# error_span(@employer[:admin_id]) %>
  </div>
-->

    <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            employers_path, :class => 'btn btn-default' %>

<% end %>

app/views/employers/edit.html.erb
<%- model_class = Employer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/employers/index.html.erb
<%- model_class = Employer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:company_name) %></th>
      <th><%= model_class.human_attribute_name(:contact_name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>

      <th><%= model_class.human_attribute_name(:admin_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <% if((cookies[:adminID]!="") && (!cookies[:adminID].is_a?NilClass)) %>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @employers.each do |employer| %>
      <tr>
        <td><%= link_to employer.id, employer_path(employer) %></td>
        <td><%= employer.company_name %></td>
        <td><%= employer.contact_name %></td>
        <td><%= employer.email %></td>

       <td><%= Admin.find(employer.admin_id).name %></td>
        <td><%=l employer.created_at %></td>

          <% if((cookies[:adminID]!="") && (!cookies[:adminID].is_a?NilClass)) %>
            <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_employer_path(employer), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      employer_path(employer),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
           </td>
          <% end %>

      </tr>
    <% end %>
  </tbody>
</table>
<%# if((cookies[:employerID]!="") && !(cookies[:employerID].is_a?NilClass) ) %>
<%# link_to t('.new', :default => t("helpers.links.new")),
            new_employer_path,
            :class => 'btn btn-primary' %>

<%# link_to "Create Jobs",new_job_path, :class => 'btn btn-primary'%>
<%# end %>

app/views/employers/new.html.erb
<%- model_class = Employer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/employers/show.html.erb
<%- model_class = Employer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:company_name) %>:</strong></dt>
  <dd><%= @employer.company_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:contact_name) %>:</strong></dt>
  <dd><%= @employer.contact_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @employer.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:password) %>:</strong></dt>
  <dd><%= @employer.password %></dd>
  <dt><strong><%= model_class.human_attribute_name(:admin_id) %>:</strong></dt>
  <dd><%= @employer.admin_id %></dd>
</dl>

<%# link_to t('.back', :default => t("helpers.links.back")),
              employers_path, :class => 'btn btn-default'  %>
<% if((cookies[:adminID]!="") && !(cookies[:adminID].is_a?NilClass)) %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_employer_path(@employer), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              employer_path(@employer),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
<% elsif((cookies[:employerID]!="") && (!cookies[:employerID].is_a?NilClass)) %>
    <%= link_to "Create Jobs",new_job_path, :class => 'btn btn-primary'%>
    <%= link_to "View Job Applications", jobapps_path(:employer_id=>@employer.id) , :class => 'btn btn-primary'%>
    <%= link_to "Change Job Application Status", jobapps_path(:employer_id => @employer.id) , :class => 'btn btn-primary' %>
<% end %>