config/routes.rb
Rails.application.routes.draw do

  resources :fields

  resources :categories

  resources :jobapplications

  resources :jobseekers

  resources :employers

  resources :jobs
  root :to => 'jobs#index'
  resources :admins
  get 'login'=>'home#login'
  post 'login_check'=> 'home#login_check'
  get 'logout' => 'home#logout'
  get 'jobapplication_lists'=>'jobapplications#list_applications'
  get '/search'=> 'jobs#search'
  get 'recommended' => 'jobs#recommendation'
  get 'jobapps'=> 'jobapplications#list_apps'
  get 'delete_employer' => 'employers#list_employer'
  get 'view_my_applications' => 'jobseekers#view_my_applications'
  match '*a', :to => 'errors#routing', via: :get

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :class => "flash_#{name}" %>
  <% end %>
<% end %>

<%#sample code from photoapp git repo%>
<%#<div class="alert alert-<%= name.to_sym == :notice ? "success" : "danger" %>
<%#<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>%>
<%#<%= content_tag :div, msg, :id => "flash_#{name}" %>
<%#</div>%>

app/views/layouts/_navigation.html.erb
<ul class="nav">


  <center><h3>Welcome to DireWolf Job Portal</h3></center>
  <nav role="navigation" class="navbar navbar-inverse">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="#" class="navbar-brand">Brand</a>
    </div>
    <!-- Collection of nav links, forms, and other content for toggling -->
    <div id="navbarCollapse" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to 'Home',root_path %></li>
        <li>
          <% if(((cookies[:adminID]!="") && (!cookies[:adminID].is_a?NilClass))) %>
              <%= link_to "Profile", admin_path(cookies[:adminID].to_i) %>
              <% elsif(((cookies[:employerID]!="") && (!cookies[:employerID].is_a?NilClass))) %>
                  <%= link_to "Profile", employer_path(cookies[:employerID].to_i) %>
          <% elsif(((cookies[:jobseekerID]!="") && (!cookies[:jobseekerID].is_a?NilClass))) %>
              <%= link_to "Profile", jobseeker_path(cookies[:jobseekerID].to_i) %>
          <% end %>
        </li>
        <li class="dropdown">
          <a data-toggle="dropdown" class="dropdown-toggle" href="#">Messages <b class="caret"></b></a>
          <ul role="menu" class="dropdown-menu">
            <li><a href="#">Inbox</a></li>
            <li><a href="#">Drafts</a></li>
            <li><a href="#">Sent Items</a></li>
            <li class="divider"></li>
            <li><a href="#">Trash</a></li>
          </ul>
        </li>
      </ul>
      <form role="search" class="navbar-form navbar-left" action="/search">
        <div class="form-group">
          <input type="text" placeholder="Search" class="form-control" name="search">
          <input type="submit" value="Search" class="btn btn-primary">
        </div>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if(
        ((cookies[:adminID]=="") || (cookies[:adminID].is_a?NilClass))&&
         (       (cookies[:employerID]=="")||( cookies[:employerID].is_a?NilClass))&&
                ((cookies[:jobseekerID]=="")|| (cookies[:jobseekerID].is_a?NilClass))
        )%>
        <li><%= link_to 'Login',login_path %></li>
        <% else %>
            <li>
            <% if((cookies[:adminID]!="") && !(cookies[:adminID].is_a?NilClass)) %>
                  <font color="white">  Welcome Admin! </font>
            <% end %>
            <% if((cookies[:employerID]!="") && !(cookies[:employerID].is_a?NilClass))%>
                  <font color="white">  Welcome Employer! </font>
            <% end %>
            <% if((cookies[:jobseekerID]!="") && !(cookies[:jobseekerID].is_a?NilClass))%>
                  <font color="white">  Welcome Jobseeker! </font>
                 <% end %>
             <%= link_to 'Logout',logout_path %>
            </li>

        <% end %>
      </ul>
    </div>
  </nav>

  <%= render 'layouts/navigation_links' %>
</ul>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Jobportal" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Jobportal" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
   <div class="container">
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>
    <footer>
      Copyrights Reserved
    </footer>
   </div>

  </body>
</html>

app/views/layouts/error.html.erb
<h3> Error</h3>
<h3><%= @custom_error %></h3>
<%= link_to "BACK", :back %>

app/views/layouts/invalid_credentials.html.erb
<h3>Invalid Credentials!</h3>
<%= link_to "BACK", 'login' %>

app/views/layouts/login.html.erb
<html>

<div class="container">
  <div class="row">
    <div class="col-sm-6 col-md-4 col-md-offset-4">
      <h1 class="text-center login-title">Sign in</h1>
      <div class="account-wall">
       <center> <img class="profile-img" src="https://lh5.googleusercontent.com/-b0-k99FZlyE/AAAAAAAAAAI/AAAAAAAAAAA/eu7opA4byxI/photo.jpg?sz=120"
             alt=""></center>
        <form class="form-signin" method="post" action="login_check">
          Email<input type="text" name="login_email" class="form-control" placeholder="Email" required autofocus>
          Password<input type="password" name="login_password" class="form-control" placeholder="Password" required>
          <div class="form_row">
            <label for="theme">Title :</label>
            <% [ 'Admin', 'Jobseeker', 'Employer' ].each do |theme| %>
                <br><%= radio_button_tag 'theme', theme, @theme == theme %>
                <%= theme.humanize %>
            <% end %>
          </div>
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
          <button class="btn btn-lg btn-primary btn-block" type="submit">
            Sign in</button>
          <label class="checkbox pull-left">
            <input type="checkbox" value="remember-me">
            Remember me
          </label>
          <a href="https://github.ncsu.edu/nkatre/jobportal" class="pull-right need-help">Need help? </a><span class="clearfix"></span>

        </form>
      </div>
      <%= link_to 'Create Account', new_jobseeker_path, {:class => "btn btn-lg btn-primary btn-block"} %>

    </div>
  </div>
</div>

</html>

app/views/layouts/logout_successful.html.erb
<center>
  <h3><%= @notification %></h3>
  <h4><%= link_to "HOME", :root %> <br></h4>
  <h4><%= link_to "LOGIN", :login %></h4>
</center>

app/views/layouts/no_recommended_jobs.html.erb
<center>
  <h3>No recommended jobs to show !</h3> <br>
</center>
  <p>
    Recommended jobs are found, by matching tags(tag1, tag2, tag3) of the jobs with your current job applications.
  </p>

  <p>
    The following can be one of the reasons for recommended jobs to be empty.

<ul>
  <li>
    You have not applied to any job previously.
  </li>
  <li>
    You have deleted all your previous job applications.
  </li>
  <li>
    The tags of the jobs does not match with the tags of your currently applied jobs
  </li>
</ul>
</p>


<h3><%= link_to "BACK", :back %></h3>

app/views/layouts/notifications.html.erb
<h3><%= @custom_notification %></h3>
<%= link_to "BACK", :back %>